spring:
  profiles:
    active:
    - dev
    
---
spring:
  #开发环境配置
  profiles: dev
  application:
    name: cloud-config-dev
    
---
spring:
  #测试环境配置
  profiles: test
  application:
    name: cloud-config-test
    
# 注意保存为 UNIX UTF-8 格式