spring:
  profiles:
    active:
    - dev
---
server:
  port: 8002
  
spring:
  profiles: dev
  application:
   name: cloud-provider
  cloud:
   nacos:
     discovery:
       server-addr: 127.0.0.1:8848

---
server:
  port: 8012
     
spring:
  profiles: test
  application:
   name: cloud-provider
  cloud:
   nacos:
     discovery:
       server-addr: 127.0.0.1:8848
